# Copyright 2026 Satisfanly Ltd
#
# OKO OS is a product of Satisfanly Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "oko-bsp-gmktec_evo_x2"
BBFILE_PATTERN_oko-bsp-gmktec_evo_x2 = "^${LAYERDIR}/"
BBFILE_PRIORITY_oko-bsp-gmktec_evo_x2 = "20"

# OKO is about AI, so always optimize relevant ai layer, therefore depend on it
# Take different bsp if u dont want to optimize for AI
# NOTE, that it also actually affects differet thinks (e.g oko-local-graphics). But it's optional, so no hard dependencies here.
LAYERDEPENDS_oko-bsp-gmktec_evo_x2 = "core openembedded-layer oko-base oko-ai"
LAYERSERIES_COMPAT_oko-bsp-gmktec_evo_x2 = "wrynose"

require ${LAYERDIR}/conf/oko-append.conf
