# Copyright 2026 Satisfanly Ltd
#
# OKO OS is a product of Satisfanly Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  ${TOPDIR}/../../poky/openembedded-core/meta \
  ${TOPDIR}/../../layers/meta-yocto/meta-poky \
  ${TOPDIR}/../../layers/meta-yocto/meta-yocto-bsp \
  ${TOPDIR}/../../layers/meta-openembedded/meta-oe \
  ${TOPDIR}/../../layers/meta-openembedded/meta-python \
  ${TOPDIR}/../../layers/meta-openembedded/meta-networking \
  ${TOPDIR}/../../layers/meta-oko-base \
  ${TOPDIR}/../../layers/meta-oko-ai \
  ${TOPDIR}/../../layers/meta-oko-image \
  ${TOPDIR}/../../layers/meta-oko-local-graphic \
  ${TOPDIR}/../../layers/meta-oko-bsp-gmktec_evo_x2 \
  "
